In [145]:
import torch

---
# 1.1 Создание тензоров
Создайте следующие тензоры:
- Тензор размером 3x4, заполненный случайными числами от 0 до 1
- Тензор размером 2x3x4, заполненный нулями
- Тензор размером 5x5, заполненный единицами
- Тензор размером 4x4 с числами от 0 до 15 (используйте reshape)

In [146]:
tensor1 = torch.rand(3, 4)
print(f"Тензор размером 3x4, заполненный случайными числами от 0 до 1: \n {tensor1}")

tensor2 = torch.zeros(2, 3, 4)
print(f"Тензор размером 2x3x4, заполненный нулями: \n {tensor2}")

tensor3 = torch.ones(5, 5)
print(f"Тензор размером 5x5, заполненный единицами: \n {tensor3}")

tensor4 = torch.arange(0, 16).reshape(4, 4)
print(f"Тензор размером 4x4 с числами от 0 до 15: \n {tensor4}")

Тензор размером 3x4, заполненный случайными числами от 0 до 1: 
 tensor([[0.6752, 0.2058, 0.5027, 0.1458],
        [0.9024, 0.9217, 0.8936, 0.3250],
        [0.8112, 0.0822, 0.7294, 0.4383]])
Тензор размером 2x3x4, заполненный нулями: 
 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Тензор размером 5x5, заполненный единицами: 
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
Тензор размером 4x4 с числами от 0 до 15: 
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])


---
# 1.2 Операции с тензорами
Дано: тензор A размером 3x4 и тензор B размером 4x3
Выполните:
- Транспонирование тензора A
- Матричное умножение A и B
- Поэлементное умножение A и транспонированного B
- Вычислите сумму всех элементов тензора A

In [147]:
A = torch.rand(3, 4, dtype = torch.float32)
B = torch.rand(4, 3, dtype = torch.float32)

a_T = A.T
print(f"Транспонирование тензора A: \n {a_T}")

matrix_multiplication = A @ B
print(f"Матричное умножение A и B: \n {matrix_multiplication}")

matrix_multiplication_2 = A * B.T
print(f"Поэлементное умножение A и транспонированного B: \n {matrix_multiplication_2}")

Транспонирование тензора A: 
 tensor([[0.0857, 0.3192, 0.6686],
        [0.0987, 0.2697, 0.4120],
        [0.0321, 0.9760, 0.8015],
        [0.5937, 0.3477, 0.6492]])
Матричное умножение A и B: 
 tensor([[0.5197, 0.3418, 0.2360],
        [1.3511, 0.8887, 0.4094],
        [1.8266, 1.2142, 0.6426]])
Поэлементное умножение A и транспонированного B: 
 tensor([[0.0700, 0.0930, 0.0210, 0.3357],
        [0.2012, 0.1252, 0.4288, 0.1334],
        [0.2611, 0.0827, 0.1035, 0.1953]])


---
# 1.3 Индексация и срезы
Создайте тензор размером 5x5x5 \
Извлеките:
- Первую строку
- Последний столбец
- Подматрицу размером 2x2 из центра тензора
- Все элементы с четными индексами

In [158]:
tensor = torch.rand(5, 5, 5)
print(f'tensor = \n {tensor}')

first_row = tensor[:1, :, :]
print(f'Первая строка: \n {first_row}')

last_column = tensor[:, :, -1:]
print(f'Последний столбец: \n {last_column}')

submatrix = tensor[1:3, 1:3, 1:3]
print(f'Подматрицу размером 2x2 из центра тензора: \n {submatrix}')

even_idx = tensor[::2, ::2, ::2]
print(f'Все элементы с четными индексами: \n {even_idx}')

tensor = 
 tensor([[[0.1067, 0.1089, 0.2690, 0.5798, 0.4421],
         [0.3667, 0.2663, 0.6301, 0.0881, 0.9919],
         [0.4226, 0.5933, 0.6647, 0.3055, 0.8946],
         [0.4963, 0.5410, 0.0240, 0.5619, 0.6716],
         [0.5697, 0.4504, 0.8775, 0.8953, 0.8442]],

        [[0.4132, 0.5864, 0.1509, 0.1257, 0.4126],
         [0.5559, 0.2088, 0.0827, 0.7275, 0.6828],
         [0.1696, 0.8327, 0.1263, 0.8782, 0.7656],
         [0.3310, 0.9760, 0.2193, 0.2716, 0.8985],
         [0.3712, 0.2981, 0.5774, 0.4155, 0.8150]],

        [[0.9082, 0.7224, 0.6081, 0.6256, 0.5130],
         [0.5587, 0.5095, 0.8409, 0.7796, 0.4497],
         [0.6888, 0.5277, 0.6767, 0.9105, 0.1598],
         [0.5711, 0.3960, 0.0112, 0.0141, 0.4345],
         [0.8579, 0.1703, 0.6629, 0.7882, 0.1356]],

        [[0.7147, 0.5944, 0.0448, 0.4904, 0.0306],
         [0.9372, 0.7343, 0.6916, 0.8839, 0.8824],
         [0.9964, 0.7063, 0.1390, 0.9644, 0.6389],
         [0.3029, 0.3139, 0.9679, 0.6111, 0.8634],
         [0.53

---
# 1.4 Работа с формами
Создайте тензор размером 24 элемента \
Преобразуйте его в формы:
- 2x12
- 3x8
- 4x6
- 2x3x4
- 2x2x2x3

In [166]:
tensor = torch.rand(24)
print(f"Тензор 1x24: \n{tensor}")

tensor_2_12 = tensor.reshape(2, 12)
print(f"Тензор 2x12: \n{tensor_2_12}")

tensor_3_8 = tensor.reshape(3, 8)
print(f"Тензор 3x8: \n{tensor_3_8}")

tensor_4_6 = tensor.reshape(4, 6)
print(f"Тензор 4x6: \n{tensor_4_6}")

tensor_2_3_4 = tensor.reshape(2, 3, 4)
print(f"Тензор 2x3x4: \n{tensor_2_3_4}")

tensor_2_2_2_3 = tensor.reshape(2, 2, 2, 3)
print(f"Тензор 2x2x2x3: \n{tensor_2_2_2_3}")

Тензор 1x24: 
tensor([0.2689, 0.8950, 0.8474, 0.5769, 0.0098, 0.1532, 0.7179, 0.8715, 0.7672,
        0.5471, 0.1959, 0.0606, 0.2143, 0.5037, 0.5659, 0.8829, 0.1394, 0.7615,
        0.9236, 0.0481, 0.2336, 0.3605, 0.5959, 0.9479])
Тензор 2x12: 
tensor([[0.2689, 0.8950, 0.8474, 0.5769, 0.0098, 0.1532, 0.7179, 0.8715, 0.7672,
         0.5471, 0.1959, 0.0606],
        [0.2143, 0.5037, 0.5659, 0.8829, 0.1394, 0.7615, 0.9236, 0.0481, 0.2336,
         0.3605, 0.5959, 0.9479]])
Тензор 3x8: 
tensor([[0.2689, 0.8950, 0.8474, 0.5769, 0.0098, 0.1532, 0.7179, 0.8715],
        [0.7672, 0.5471, 0.1959, 0.0606, 0.2143, 0.5037, 0.5659, 0.8829],
        [0.1394, 0.7615, 0.9236, 0.0481, 0.2336, 0.3605, 0.5959, 0.9479]])
Тензор 4x6: 
tensor([[0.2689, 0.8950, 0.8474, 0.5769, 0.0098, 0.1532],
        [0.7179, 0.8715, 0.7672, 0.5471, 0.1959, 0.0606],
        [0.2143, 0.5037, 0.5659, 0.8829, 0.1394, 0.7615],
        [0.9236, 0.0481, 0.2336, 0.3605, 0.5959, 0.9479]])
Тензор 2x3x4: 
tensor([[[0.2689, 0.8950, 0